volumes:
  mongo:

services:
  web:
    restart: on-failure
    image: bqat-gui:latest
    # image: ghcr.io/biometix/bqat-gui:latest
    build:
      context: web
    ports:
      - 7860:7860
    depends_on:
      - api
  
  # web-lite:
  #   restart: on-failure
  #   image: bqat-gui-lite:latest
  #   # image: ghcr.io/biometix/bqat-gui-lite:latest
  #   build:
  #     context: lite/bqat_gui
  #   ports:
  #     - 7860:7860
  #   depends_on:
  #     - api
      
  api:
    restart: on-failure
    image: bqat-api:1.4
    # image: ghcr.io/biometix/bqat-api:latest
    shm_size: '8gb'
    depends_on:
      - mongo
      - redis
    environment:
      MGO_URL: mongodb://root:admin@mongo:27017/
      SCAN_DB: scan
      LOG_DB: log
      RDS_URL: redis://redis:6379/
      QUEUE_DB: 10
      DATA: data/
      WEB: http://localhost:7860
    ports:
      - 8848:8848
    volumes:
      - ./data:/app/data
  
  redis:
    restart: on-failure
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    restart: on-failure
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo:/data/db

  mongo-express:
    restart: on-failure
    image: mongo-express:latest
    build:
      context: https://github.com/mongo-express/mongo-express.git
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_SITE_COOKIESECRET: 'cookiesecret'
      ME_CONFIG_SITE_SESSIONSECRET: 'sessionsecret'
